baseurl = "https://tan-furukawa.github.io/niconavi/"
title = "NicoNavi"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[module]
  [[module.mounts]]
    source = "themes/hugo-coder/layouts/_partials"
    target = "layouts/partials"
  [[module.mounts]]
    source = "themes/hugo-coder/layouts/_shortcodes"
    target = "layouts/shortcodes"
  [[module.mounts]]
    source = "themes/hugo-coder/layouts/_markup"
    target = "layouts/_default/_markup"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "NicoNavi"
  info = "For Quantitative Analysis of Micorostructure Using a Polarizing Microscope"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.png"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  # since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/johndoe/"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Install"
  weight = 2
  url  = "install/"
[[menu.main]]
  name = "Data Acquisition"
  weight = 3
  url  = "acquisition/"
[[menu.main]]
  name = "Tutorial"
  weight = 4
  url  = "tutorial/"

[languages.en]
languageName = "EN"

[languages.ja]
languageName = "JA"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$','$']]
